#!/bin/bash
set -e

if ! [ -L ~/.gnupg ] || ! [ -L ~/.ssh ]
then
  echo "Run script/setup first!" >&2
  exit 1
fi

onepassword_login() {
  if ! command -v op >/dev/null
  then
    echo "Install op first!" >&2
    exit 1
  fi

  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_alpha_numeric" ]
  then
    echo "Logging into 1Password..."
    eval "$(op signin)"
  fi
}

onepassword_get() {
  if [ -f "$HOME/$2" ]
  then
    echo "$2 already exists."
    return
  fi
  echo "Extracting $2..."
  onepassword_login
  op document get "$1" > "$HOME/$2"
  chmod 600 "$HOME/$2"
}

onepassword_get ycwrzjsjnnczxetoj7lcnzgunu .ssh/id_ed25519
onepassword_get lvj6ngestzfijcwqjvtbn4vq4m .ssh/id_rsa
onepassword_get d2ijce4mrfgjtkgbkmmrzngvbq .gnupg/tom.krouper@gmail.com.private.gpg-key

if ! [ -f "$HOME/.secrets" ]
then
  echo "Extracting secrets..."
  if ! command -v jq >/dev/null
  then
    echo "Install jq first!" >&2
    exit 1
  fi
  onepassword_login
  BINTRAY_KEY=$(op item get t6wkb3pguncltiehjfoeft3r6q | jq -r '.details.sections[1].fields[].v')
  GITHUB_TOKEN=$(op item get g6klazxi3ffprbnou2mexznlay | jq -r '.details.sections[1].fields[].v')
  cat > "$HOME/.secrets" <<EOF
export BINTRAY_KEY=$BINTRAY_KEY
export GITHUB_TOKEN=$GITHUB_TOKEN
EOF
  chmod 600 "$HOME/.secrets"
fi

echo "Storing SSH keys in keychain..."
ssh-add --apple-use-keychain

echo "Setting up GPG..."
if ! command -v gpg >/dev/null
then
    echo "Install GPG first!" >&2
    exit 1
fi

chmod 700 ~/.gnupg
gpg --batch --import ~/.gnupg/tom.krouper@gmail.com.public.gpg-key \
             ~/.gnupg/tom.krouper@gmail.com.private.gpg-key
