#!/bin/sh
# Install all dotfiles into the home directory

DOTFILESDIRREL=$(dirname "$0")
cd "$DOTFILESDIRREL"/.. || exit
DOTFILESDIR=$(pwd -P)

for DOTFILE in *; do
  HOMEFILE="$HOME/.$DOTFILE"
  [ -d "$DOTFILE" ] && DOTFILE="$DOTFILE/"
  DIRFILE="$DOTFILESDIR/$DOTFILE"

  echo "$DOTFILE" | grep -qE '(^script/$|\.txt$|\.md$)' && continue
  echo "$DOTFILE" | grep -q '\.sh' &&
    HOMEFILE="$HOME/.$(echo "$DOTFILE" | sed -e 's/\.sh//')"

  if [ -f "$HOMEFILE" ] || [ -d "$HOMEFILE" ]; then
    cp "$HOMEFILE" "${HOMEFILE}-$(date +%Y%m%d%H%M%S)"
  fi
  if [ -L "$HOMEFILE" ] && ! [ -d "$DOTFILE" ]; then
    ln -sfv "$DIRFILE" "$HOMEFILE"
  else
    rm -rv "$HOMEFILE"
    ln -sv "$DIRFILE" "$HOMEFILE"
  fi
done
